server:
  port: 9997
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: nacos:192.168.163.129:8848
  cloud:
    nacos:
       server-addr: 192.168.163.129:8848
       discovery:
         ip: 127.0.0.1
    gateway:
     routes:
       - id: item-service
         uri: lb://item-service
         predicates:
           - Path=/shop/**
       - id: user-service
         uri: lb://user-service
         predicates:
           - Path=/user/**,/common/**
       - id: order-service
         uri: lb://order-service
         predicates:
           - Path=/order/**
       - id: address-service
         uri: lb://address-service
         predicates:
           - Path=/address/**
       - id: cart-service
         uri: lb://cart-service
         predicates:
           - Path=/cart/**
       - id: promotion-service
         uri: lb://promotion-service
         predicates:
           - Path=/promotion/**